In [41]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from sklearn.model_selection import GridSearchCV


In [42]:
labels = pd.read_csv('labels.csv', compression='zip')
features = pd.read_csv('features.csv', compression='zip')
labels_gen = pd.read_csv('labels_gen.csv', compression='zip')
features_gen = pd.read_csv('features_gen.csv', compression='zip')
labels_gen_no_clear = pd.read_csv('labels_gen_no_clear.csv', compression='zip')
features_gen_no_clear = pd.read_csv('features_gen_no_clear.csv', compression='zip')

labels.drop(['Unnamed: 0'],axis=1, inplace=True)
features.drop(['Unnamed: 0'],axis=1, inplace=True)
labels_gen.drop(['Unnamed: 0'],axis=1, inplace=True)
features_gen.drop(['Unnamed: 0'],axis=1, inplace=True)
labels_gen_no_clear.drop(['Unnamed: 0'],axis=1, inplace=True)
features_gen_no_clear.drop(['Unnamed: 0'],axis=1, inplace=True)

In [43]:
labels_gen['weather_description'][0]

'Cloudy'

In [44]:
features_gen.head()

humidity  temperature  pressure  wind direction  wind speed  Latitude  \
0      87.0   284.590217     807.0           268.0         0.0  49.24966   
1      88.0   284.588174     849.0           281.0         0.0  49.24966   
2      89.0   284.586130     890.0           295.0         0.0  49.24966   
3      89.0   284.584087     932.0           309.0         0.0  49.24966   
4      90.0   284.582043     973.0           323.0         0.0  49.24966   

    Longitude  month  day  hour  day_avg_hum  month_avg_hum  year_avg_hum  \
0 -123.119339     10    2     9    67.822292      67.819934     67.756567   
1 -123.119339     10    2    10    67.822292      67.819934     67.756567   
2 -123.119339     10    2    11    67.822292      67.819934     67.756567   
3 -123.119339     10    2    12    67.822292      67.819934     67.756567   
4 -123.119339     10    2    13    67.822292      67.819934     67.756567   

   day_avg_temp  month_avg_temp  year_avg_temp  day_avg_press  \
0     287.58953      287.593295     287.600263    1018.114301   
1     287.58953      287.593295     287.600263    1018.114301   
2     287.58953      287.593295     287.600263    1018.114301   
3     287.58953      287.593295     287.600263    1018.114301   
4     287.58953      287.593295     287.600263    1018.114301   

   month_avg_press  year_avg_press  
0      1018.116066     1018.091305  
1      1018.116066     1018.091305  
2      1018.116066     1018.091305  
3      1018.116066     1018.091305  
4      1018.116066     1018.091305

In [45]:
labels_2 = labels

In [46]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(features_gen_no_clear, labels_gen_no_clear, test_size = 0.25, random_state = 21)

In [47]:
# Feature Scaling
#scaler = StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.transform(X_test)

In [48]:
parameters = {
    'n_estimators'      : [100,130],
    #'max_features': ['auto'],
    #'criterion' :['gini']
}

#clf = GridSearchCV(RandomForestClassifier(), parameters, cv=5, n_jobs=-1)
#clf.fit(X_train, y_train)

# Fitting Random Forest Classification to the Training set
classifier = RandomForestClassifier(n_estimators = 100, oob_score = True, n_jobs = -1,random_state =50,                                         max_features = "auto", verbose=True)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  3.6min finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    2.8s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    6.5s finished


In [49]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[113462    684     23   9686    503    105      0]
 [  2912   3374     35   3411     72     10      0]
 [   125     40    389     37      0      0      0]
 [ 14984   1242     16  54719    299    167      0]
 [  1370     61      0    586   3333      0      0]
 [  1127     10      1    712      0    185      0]
 [     0      0      0      1      0      0      0]]
                 precision    recall  f1-score   support

         Cloudy       0.85      0.91      0.88    124463
       Fog/Haze       0.62      0.34      0.44      9814
Poor Visibility       0.84      0.66      0.74       591
          Rainy       0.79      0.77      0.78     71427
           Snow       0.79      0.62      0.70      5350
         Stormy       0.40      0.09      0.15      2035
  Weather Event       0.00      0.00      0.00         1

       accuracy                           0.82    213681
      macro avg       0.61      0.48      0.53    213681
   weighted avg       0.81      0.82      0.81    213681

0.821

In [50]:
y_pred

array(['Rainy', 'Cloudy', 'Snow', ..., 'Cloudy', 'Cloudy', 'Rainy'],
      dtype=object)

In [51]:
labels

weather_description
0             broken clouds
1             broken clouds
2             broken clouds
3             broken clouds
4             broken clouds
...                     ...
1330433       broken clouds
1330434       broken clouds
1330435       broken clouds
1330436          few clouds
1330437       broken clouds

[1330438 rows x 1 columns]

In [52]:
labels.head()

weather_description
0       broken clouds
1       broken clouds
2       broken clouds
3       broken clouds
4       broken clouds